name: MAVEN DEPLOYMENT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: oym
    permissions:
      contents: read
      packages: write    

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Maven Deploy
      #  env:
      #    OYM_USERNAME: ${{ secrets.OYM_USERNAME }}
      #    OYM_PASSWORD: ${{ secrets.OYM_PASSWORD }}
        run: |
          echo $OYM_USERNAME
          mvn deploy -s maven-settings.xml -DskipTests -P javadoc
