name: MAVEN DEPLOYMENT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Setup password and username
        run: |
          if [[ -f "maven-settings.xml" ]]; then
            sed -i "s/{OYM_USERNAME}/${{ secrets.OYM_USERNAME }}/g" maven-settings.xml
            sed -i "s/{OYM_PASSWORD}/${{ secrets.OYM_PASSWORD }}/g" maven-settings.xml
          else
            echo "maven-settings.xml file not found!"
            exit 1
          fi

      - name: Running tests and deploying
        run: |
          mvn deploy -s maven-settings.xml -DskipTests -P javadoc
