name: MAVEN DEPLOYMENT

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: oym
    permissions:
      contents: read
      packages: write    

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Maven Deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OYM_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OYM_PASSWORD }}
        run: |
          mvn deploy -DskipTests -P javadoc